language: node_js
node_js:
  - 10.19

branches:
  only:
    - master
    - type=pull_request

before_install:
  - npm install

deploy:
  provider: npm
  on:
    branch: master
  email: 'gkabitakis@gmail.com'
  api_key: ${NPM_TOKEN}
  skip_cleanup: true